### ISSUE TITLE
Text as CDATA?

### ISSUE THREAD

**Issue by tmcw** [JoshData/dc-code-prototype#1]
I'm not sure, but it seems like having an XML->seamlesslyinto->HTML format might be problematic for parsing - I wonder if text contents should usually/aways be wrapped in CDATA blocks?

**Comment by tmcw** [comment]
(also the inevitable presence of `<`, `>`, and `&`)

**Comment by JoshData** [comment]
Not sure I see the problem.... CDATA doesn't really change the semantics.

**Comment by tmcw** [comment]
Hm, it would - without CDATA structure for, let's say, a description element would look like
- description
  - textNode
  - span
  - textNode

With CDATA, would be
- description
  - textNode

**Comment by JoshData** [comment]
Oh for spans. Ok. But I still don't see the actual problem...? Do you mean because rendering a mixed-content element is hard?
