### ISSUE TITLE
Parser/generator?

### ISSUE THREAD

**Issue by tmcw** [JoshData/dc-code-prototype#3]
How were these files generated? For any new formats it's always nice to have reference implementations.

**Comment by JoshData** [comment]
Ok. I think that will go in a separate repo for tools. This came from a new/updated Word doc provided by Lexis. I scraped the .docx file.

**Comment by JoshData** [comment]
See: https://github.com/JoshData/dc-code-prototype-tools

@vzvenyach: Can we post the Lexis .docx file somwhere?

**Comment by vdavez** [comment]
Yes. I'll try and get it on the website. In the meantime, I'll post it here: https://github.com/vzvenyach/Code_PrimaryDocs/blob/master/PrimaryDocs/DC_Code_Sept_2013.docx

**Comment by JoshData** [comment]
I added a link to the README of the tools project in a919ce9, so I think that takes care of this issue. Thanks Tom.
