### ISSUE TITLE
Clean up the <text> classes

### ISSUE THREAD

**Issue by JoshData** [JoshData/dc-code-prototype#4]
The form, formc, table, tablec, and PlainText attributes are coming from the data source. Not sure what they mean.

**Comment by JoshData** [comment]
fixed in 745994ea0d5d6ce7f458598d53e6954d39100880 55c01eab4b564076c51890f913bd677d637edbf1 bbb92d5f5751f1ec9e30fe2b6a353e263f7e3db4

**Comment by vdavez** [comment]
Ah! I think I know what this is... These refer to situations where the Code is incorporating the text of another legal document. For example, the WMATA compact or a Reorganization Plan. Let me double check whether there's a reason to maintain the formatting just so...

**Comment by JoshData** [comment]
It's more like this:

http://joshdata.github.io/dc-code-prototype/Division-I/Title-1/Chapter-2/Subchapter-IV/Part-E/Subpart-1/1-204.63.xml
("form")

and

http://joshdata.github.io/dc-code-prototype/Division-I/Title-1/Chapter-6/Subchapter-XXVI/1-626.10.xml
("table")

Anyway, it's slightly less messy today than yesterday.
