### ISSUE TITLE
Appendices has @@@PICT@@@ in it

### ISSUE THREAD

**Issue by JoshData** [JoshData/dc-code-prototype#6]
Gotta fix whatever this was about:

https://github.com/JoshData/dc-code-prototype/blob/02b5489dc9e4a366ce41c15fe087cc06d8ad33df/Division-II/Title-16/Chapter-9/16-916.01.xml

**Comment by GPHemsley** [comment]
Note also that the &lt;text> element seems to contain only what the &lt;heading> element represents.
